# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1282, 789)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QProgressBar {\n"
"    border: 2px solid #ccc; /* Light gray border to match other elements */\n"
"    border-radius: 5px; /* Rounded corners for smooth look */\n"
"    background: #f3f3f3; /* Light gray background */\n"
"    text-align: center; /* Center the progress text */\n"
"    color: #fff; /* White text color for contrast */\n"
"    font-family: Arial, sans-serif; /* Font style */\n"
"    font-size: 12px; /* Font size */\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color:#e53935; /* Solid red color for the progress */\n"
"    border-radius: 5px; /* Smooth rounded edges for the bar */\n"
"}\n"
"\n"
"\n"
"/* Apply to the entire application */\n"
"QWidget {\n"
"    background-color: #1c1c1c; /* Dark gray background */\n"
"    color: #f0f0f0; /* Light text color */\n"
"\n"
"}\n"
"\n"
"/* Apply to labels */\n"
"QLabel {\n"
"    color: #f44336; /* Bright red text color */\n"
"    font-size: 16px; /* Adjusted font size for labels */\n"
"    padding: 5px; /* Add padding for labels */\n"
"}\n"
"\n"
"/* Apply to buttons */\n"
"QPushButton {\n"
"    background-color: #d32f2f; /* Bright red background */\n"
"    border: none; /* No border */\n"
"    color: #ffffff; /* White text color */\n"
"\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    font-size: 14px; /* Adjust font size */\n"
"    margin: 5px; /* Margin around buttons */\n"
"    transition: background-color 0.3s ease; /* Smooth transition */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e53935; /* Slightly brighter red on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #b71c1c; /* Darker red when pressed */\n"
"}\n"
"\n"
"/* Apply to form frame */\n"
"QFrame#formFrame {\n"
"    background-color: #2e2e2e; /* Slightly lighter gray for formFrame */\n"
"    border: 2px solid #d32f2f; /* Bright red border */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    padding: 15px; /* Padding inside the frame */\n"
"    margin: 10px; /* Margin around frame */\n"
"}\n"
"\n"
"/* Apply to tab widget */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #d32f2f; /* Bright red border around tab pane */\n"
"    background-color: #1c1c1c; /* Dark background for tab pane */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    padding: 10px; /* Padding inside the tab pane */\n"
"}\n"
"\n"
"\n"
"QTabBar::tab {\n"
"    background: #2e2e2e; /* Dark gray background for tabs */\n"
"    color: #f0f0f0; /* Light text color */\n"
"    border: 1px solid #d32f2f; /* Bright red border */\n"
"    border-bottom-color: #1c1c1c; /* Same as pane background to blend */\n"
"    border-radius: 5px 5px 0 0; /* Rounded top corners */\n"
"    padding: 8px 16px; /* Padding inside tabs */\n"
"    margin: 2px; /* Margin between tabs */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #d32f2f; /* Bright red background for selected tab */\n"
"    color: #ffffff; /* White text color for selected tab */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: #e53935; /* Slightly brighter red on hover */\n"
"}\n"
"\n"
"/* Optional: Style for QLineEdit, QComboBox, etc. */\n"
"QLineEdit, QComboBox {\n"
"    background-color: #3e3e3e; /* Dark gray background */\n"
"    border: 1px solid #d32f2f; /* Bright red border */\n"
"    border-radius: 5px; /* Rounded corners */\n"
"    color: #f0f0f0; /* Light text color */\n"
"    padding: 5px; /* Padding inside the input */\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.TerminalTextEdit = TerminalTextEdit(self.centralwidget)
        self.TerminalTextEdit.setMinimumSize(QtCore.QSize(400, 500))
        self.TerminalTextEdit.setMaximumSize(QtCore.QSize(430, 16777215))
        self.TerminalTextEdit.setObjectName("TerminalTextEdit")
        self.gridLayout.addWidget(self.TerminalTextEdit, 0, 0, 4, 3)
        self.plotWidget = PlotWidget(self.centralwidget)
        self.plotWidget.setMinimumSize(QtCore.QSize(450, 550))
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout.addWidget(self.plotWidget, 0, 3, 6, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(360, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 4, 1, 1)
        self.comPortComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comPortComboBox.setMaximumSize(QtCore.QSize(210, 16777215))
        self.comPortComboBox.setObjectName("comPortComboBox")
        self.gridLayout.addWidget(self.comPortComboBox, 1, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 4, 1, 1)
        self.baudRateComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.baudRateComboBox.setMaximumSize(QtCore.QSize(210, 16777215))
        self.baudRateComboBox.setObjectName("baudRateComboBox")
        self.gridLayout.addWidget(self.baudRateComboBox, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 4, 1, 1)
        self.windowSizeSlider = QtWidgets.QSlider(self.centralwidget)
        self.windowSizeSlider.setMaximumSize(QtCore.QSize(210, 16777215))
        self.windowSizeSlider.setSliderPosition(50)
        self.windowSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.windowSizeSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.windowSizeSlider.setObjectName("windowSizeSlider")
        self.gridLayout.addWidget(self.windowSizeSlider, 3, 5, 1, 1)
        self.CMDtextEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CMDtextEdit.setObjectName("CMDtextEdit")
        self.gridLayout.addWidget(self.CMDtextEdit, 4, 0, 1, 2)
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendButton.setMinimumSize(QtCore.QSize(130, 50))
        self.SendButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.SendButton.setObjectName("SendButton")
        self.gridLayout.addWidget(self.SendButton, 4, 2, 1, 1)
        self.BondlistButton = QtWidgets.QPushButton(self.centralwidget)
        self.BondlistButton.setMinimumSize(QtCore.QSize(0, 50))
        self.BondlistButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.BondlistButton.setObjectName("BondlistButton")
        self.gridLayout.addWidget(self.BondlistButton, 5, 0, 1, 1)
        self.PairButton = QtWidgets.QPushButton(self.centralwidget)
        self.PairButton.setMinimumSize(QtCore.QSize(0, 50))
        self.PairButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.PairButton.setObjectName("PairButton")
        self.gridLayout.addWidget(self.PairButton, 5, 1, 1, 1)
        self.PassiveButton = QtWidgets.QPushButton(self.centralwidget)
        self.PassiveButton.setMinimumSize(QtCore.QSize(0, 50))
        self.PassiveButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.PassiveButton.setObjectName("PassiveButton")
        self.gridLayout.addWidget(self.PassiveButton, 5, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setMaximumSize(QtCore.QSize(200, 100))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/newPrefix/logo.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 5, 5, 2, 1)
        self.FactoryResetButton = QtWidgets.QPushButton(self.centralwidget)
        self.FactoryResetButton.setMinimumSize(QtCore.QSize(0, 50))
        self.FactoryResetButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.FactoryResetButton.setObjectName("FactoryResetButton")
        self.gridLayout.addWidget(self.FactoryResetButton, 6, 0, 1, 1)
        self.ResetButton = QtWidgets.QPushButton(self.centralwidget)
        self.ResetButton.setMinimumSize(QtCore.QSize(0, 50))
        self.ResetButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.ResetButton.setObjectName("ResetButton")
        self.gridLayout.addWidget(self.ResetButton, 6, 1, 1, 1)
        self.HelpButton = QtWidgets.QPushButton(self.centralwidget)
        self.HelpButton.setMinimumSize(QtCore.QSize(0, 50))
        self.HelpButton.setMaximumSize(QtCore.QSize(130, 16777215))
        self.HelpButton.setObjectName("HelpButton")
        self.gridLayout.addWidget(self.HelpButton, 6, 2, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.ClearButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClearButton.setMinimumSize(QtCore.QSize(0, 50))
        self.ClearButton.setObjectName("ClearButton")
        self.horizontalLayout_13.addWidget(self.ClearButton)
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setMinimumSize(QtCore.QSize(0, 50))
        self.SaveButton.setObjectName("SaveButton")
        self.horizontalLayout_13.addWidget(self.SaveButton)
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setMinimumSize(QtCore.QSize(0, 50))
        self.StartButton.setObjectName("StartButton")
        self.horizontalLayout_13.addWidget(self.StartButton)
        self.gridLayout.addLayout(self.horizontalLayout_13, 6, 3, 1, 1)
        self.LogButton = QtWidgets.QPushButton(self.centralwidget)
        self.LogButton.setMinimumSize(QtCore.QSize(130, 50))
        self.LogButton.setMaximumSize(QtCore.QSize(360, 16777215))
        self.LogButton.setObjectName("LogButton")
        self.gridLayout.addWidget(self.LogButton, 6, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Plotter v1.1.0"))
        self.label_4.setText(_translate("MainWindow", "Port 1 Configuration"))
        self.label_2.setText(_translate("MainWindow", "COM port"))
        self.label.setText(_translate("MainWindow", "Baud rate"))
        self.label_3.setText(_translate("MainWindow", "Display window"))
        self.SendButton.setText(_translate("MainWindow", "Send"))
        self.BondlistButton.setText(_translate("MainWindow", "Bond List"))
        self.PairButton.setText(_translate("MainWindow", "Pair"))
        self.PassiveButton.setText(_translate("MainWindow", "Passive entry"))
        self.FactoryResetButton.setText(_translate("MainWindow", "Factory reset"))
        self.ResetButton.setText(_translate("MainWindow", "Reset"))
        self.HelpButton.setText(_translate("MainWindow", "Help"))
        self.ClearButton.setText(_translate("MainWindow", "Clear"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.LogButton.setText(_translate("MainWindow", "Log"))
from plotter import TerminalTextEdit
from pyqtgraph import PlotWidget
import icon
import logo
